import { mkdir, writeFile } from "node:fs/promises";
import { writeFile as writeFileCallback } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const CODEPOINTS_URL =
  "https://raw.githubusercontent.com/google/material-design-icons/refs/heads/master/variablefont/MaterialSymbolsOutlined%5BFILL%2CGRAD%2Copsz%2Cwght%5D.codepoints";

// Base URL for the variable font directory in the upstream repo
const VARIABLE_FONT_BASE =
  "https://raw.githubusercontent.com/google/material-design-icons/refs/heads/master/variablefont";

// Styles we want to fetch fonts for
const FONT_STYLES = [
  { style: "Outlined", slug: "outlined" },
  { style: "Rounded", slug: "rounded" },
  { style: "Sharp", slug: "sharp" },
];

const GENERATED_DIR = "../packages/tailwindcss-material-symbols/src/generated";
const ASSETS_DIR = "../packages/tailwindcss-material-symbols/assets";

interface IconEntry {
  name: string;
  codepoint: string; // 4+ hex digits, lowercase
}

async function fetchCodepoints(): Promise<IconEntry[]> {
  const res = await fetch(CODEPOINTS_URL);
  if (!res.ok) throw new Error(`Failed to download codepoints: ${res.status} ${res.statusText}`);
  const text = await res.text();
  return text
    .split(/\r?\n/) // lines
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith("#"))
    .map((l) => {
      const [name, hex] = l.split(/\s+/);
      if (!name || !hex) return null;
      return { name, codepoint: hex.toLowerCase() } satisfies IconEntry | null;
    })
    .filter((x): x is IconEntry => !!x)
    .sort((a, b) => a.name.localeCompare(b.name));
}

function generateTS(entries: IconEntry[]): string {
  const lines: string[] = [];
  lines.push("/* Auto-generated by scripts/update-codepoints.ts. Do not edit manually. */");
  lines.push("// prettier-ignore");
  lines.push("export const codepoints = {");
  for (const { name, codepoint } of entries) {
    // In TS we use the full unicode escape with leading \u and zero-pad to at least 4 digits (Material hex values already 4+)
    const uni = "\\u" + codepoint.padStart(4, "0");
    lines.push(`  "${name}": "${uni}",`);
  }
  lines.push("} as const;\n");
  lines.push("export default codepoints;\n");
  return lines.join("\n");
}

function generateCSS(entries: IconEntry[]): string {
  const lines: string[] = [];
  lines.push("/* Auto-generated by scripts/update-codepoints.ts. Do not edit manually. */");
  lines.push("@theme {");
  for (const { name, codepoint } of entries) {
    // CSS expects escaped sequence inside quotes: "\e951" (no leading u, 1 backslash)
    const cssEsc = `\\${codepoint}`; // single backslash in output
    lines.push(`  --icon-symbol-${name}: "${cssEsc}";`);
  }
  lines.push("}\n");
  return lines.join("\n");
}

async function writeOutputs(entries: IconEntry[]) {
  const outDir = fileURLToPath(new URL(GENERATED_DIR, import.meta.url));
  await mkdir(outDir, { recursive: true });
  await Promise.all([
    writeFile(resolve(outDir, "codepoints.ts"), generateTS(entries), "utf8"),
    writeFile(resolve(outDir, "codepoints.css"), generateCSS(entries), "utf8"),
  ]);
}

function buildRemoteFontFileName(style: string): string {
  // Matches upstream naming pattern: MaterialSymbols<Style>[FILL,GRAD,opsz,wght].woff2 with encoded brackets & commas
  return `MaterialSymbols${style}%5BFILL%2CGRAD%2Copsz%2Cwght%5D.woff2`;
}

async function downloadFont(style: string, slug: string, destDir: string): Promise<void> {
  const remoteName = buildRemoteFontFileName(style);
  const url = `${VARIABLE_FONT_BASE}/${remoteName}`;
  const fileName = `material-symbols-${slug}.woff2`;
  const filePath = resolve(destDir, fileName);

  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Failed to download font ${style}: ${res.status} ${res.statusText}`);
  }
  const buf = Buffer.from(await res.arrayBuffer());
  await new Promise<void>((resolvePromise, rejectPromise) => {
    writeFileCallback(filePath, buf, (err) => (err ? rejectPromise(err) : resolvePromise()));
  });
}

async function downloadFonts(): Promise<string[]> {
  const outDir = fileURLToPath(new URL(ASSETS_DIR, import.meta.url));
  await mkdir(outDir, { recursive: true });
  await Promise.all(FONT_STYLES.map(({ style, slug }) => downloadFont(style, slug, outDir)));
  return FONT_STYLES.map(({ slug }) => `material-symbols-${slug}.woff2`);
}

try {
  console.log("Downloading Material Symbols codepoints...");
  const entries = await fetchCodepoints();
  console.log(`Fetched ${entries.length} entries. Generating codepoint files...`);
  await writeOutputs(entries);
  console.log("Generated src/generated/codepoints.ts & codepoints.css");
  console.log("Downloading variable font files (outlined, rounded, sharp)...");
  const fontFiles = await downloadFonts();
  console.log("Downloaded fonts:", fontFiles.join(", "));
} catch (err) {
  console.error(err);
  process.exitCode = 1;
}
